CREATE DATABASE UNIVERSITY

CREATE SCHEMA db_univer

CREATE TABLE db_univer.COURSES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(500)
)

CREATE TABLE db_univer.GROUPS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    COURSE_ID INT FOREIGN KEY REFERENCES db_univer.COURSES(ID),
    NAME VARCHAR(10) NOT NULL 
)

CREATE TABLE db_univer.STUDENTS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    GROUP_ID INT FOREIGN KEY REFERENCES db_univer.GROUPS(ID),
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL 
)
