INSERT INTO db_univer.COURSES (NAME, DESCRIPTION)
VALUES ('Space Engineering', 'Department of Space Engineering'),
       ('Aircraft', 'Department of Aircraft Control Systems'),
       ('Chemical Engineering', 'Faculty of Chemical Engineering'),
       ('Machine Design', 'Department of Machine Design'),
       ('Engineering Department', 'Electronic Engineering Department')

INSERT INTO db_univer.GROUPS(COURSE_ID, NAME)
VALUES (1, 'SE-01'),
       (1, 'SE-02'),
       (1, 'SE-03'),
       (2, 'AC-01'),
       (2, 'AC-02'),
       (2, 'AC-03'),
       (3, 'CE-01'),
       (3, 'CE-02'),
       (3, 'CE-03'),
       (5, 'SR-01'),
       (5, 'SR-02'),
       (5, 'SR-03'),
       (4, 'DC-01'),
       (4, 'DC-02'),
       (4, 'DC-03')
       

INSERT INTO db_univer.STUDENTS (GROUP_ID, FIRST_NAME, LAST_NAME)
VALUES (1, 'Tony', 'Stark'),
       (1, 'Hank', 'Pym'),
       (1, 'Janet', 'Pym'),
       (1, 'Bruce', 'Banner'),
       (1, 'Thor', 'Odinson'),
       (1, 'Rick', 'Jones'),
       (2, 'Steven', 'Rogers'),
       (2, 'Francis', 'Barton'),
       (2, 'Pietro', 'Maximoff'),
       (2, 'Wanda', 'Maximoff'),
       (2, 'Harry', 'Cleese'),
       (2, 'Victor', 'Shade'),
       (2, 'Dane', 'Whitman'),
       (3, 'Natasha', 'Romanoff'),
       (3, 'Henry', 'McCoy'),
       (3, 'Heather', 'Douglas'),
       (3, 'Patsy', 'Walker'),
       (3, 'Matthew', 'Liebowitz'),
       (3, 'Patsy', 'Walker'),
       (3, 'Simon', 'Williams'),
       (4, 'Aleta', 'Ogord'),
       (4, 'Martinex', 'T''Naga'),
       (4, 'Nicholette', 'Gold'),
       (4, 'Vance', 'Astrovik'),
       (5, 'Yondu', 'Udonta'),
       (5, 'Mar', 'Vell'),
       (5, 'Carol', 'Danvers'),
       (5, 'Samuel', 'Wilson'),
       (13, 'Jennifer', 'Walters'),
       (13, 'Monica', 'Rambeau'),
       (13, 'James', 'Rhodes'),
       (13, 'Barbara', 'Barton'),
       (13, 'Moira', 'Brandon'),
       (13, 'Bonita', 'Juarez'),
       (13, 'Marc', 'Spector'),
       (13, 'John', 'Walker'),
       (13, 'Jim', 'Hammond'),
       (13, 'Miguel', 'Santos'),
       (13, 'Julia', 'Carpenter'),
       (13, 'Christopher', 'Powell')
