INSERT INTO db_univer.COURSES (NAME, DESCRIPTION)
VALUES ('Maths', 'natural sciences'),
       ('English', 'philology'),
       ('Physics', 'natural sciences'),
       ('Chemistry', 'natural sciences'),
       ('Biology', 'natural sciences'),
       ('History', 'philology'),
       ('Geography', 'philology'),
       ('Music', 'philology')

INSERT INTO db_univer.GROUPS(NAME)
VALUES ('MU-01'),
       ('MU-02'),
       ('MU-03'),
       ('SR-01'),
       ('SR-02'),
       ('SR-03')

INSERT INTO db_univer.GROUPS_COURSES(GROUP_ID, COURSE_ID)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (2, 1),
       (2, 2),
       (2, 3),
       (3, 4),
       (3, 5),
       (3, 6),
       (3, 7),
       (3, 8),
       (4, 8),
       (5, 8),
       (6, 8)

INSERT INTO db_univer.STUDENTS (GROUP_ID, FIRST_NAME, LAST_NAME)
VALUES (1, 'Tony', 'Stark'),
       (1, 'Hank', 'Pym'),
       (1, 'Janet', 'Pym'),
       (1, 'Bruce', 'Banner'),
       (1, 'Thor', 'Odinson'),
       (1, 'Rick', 'Jones'),
       (2, 'Steven', 'Rogers'),
       (2, 'Francis', 'Barton'),
       (2, 'Pietro', 'Maximoff'),
       (2, 'Wanda', 'Maximoff'),
       (2, 'Harry', 'Cleese'),
       (2, 'Victor', 'Shade'),
       (2, 'Dane', 'Whitman'),
       (3, 'Natasha', 'Romanoff'),
       (3, 'Henry', 'McCoy'),
       (3, 'Heather', 'Douglas'),
       (3, 'Patsy', 'Walker'),
       (3, 'Matthew', 'Liebowitz'),
       (3, 'Patsy', 'Walker'),
       (3, 'Simon', 'Williams'),
       (4, 'Aleta', 'Ogord'),
       (4, 'Martinex', 'T''Naga'),
       (4, 'Nicholette', 'Gold'),
       (4, 'Vance', 'Astrovik'),
       (6, 'Yondu', 'Udonta'),
       (6, 'Mar', 'Vell'),
       (6, 'Carol', 'Danvers'),
       (6, 'Samuel', 'Wilson'),
       (5, 'Jennifer', 'Walters'),
       (5, 'Monica', 'Rambeau'),
       (5, 'James', 'Rhodes'),
       (5, 'Barbara', 'Barton'),
       (5, 'Moira', 'Brandon'),
       (5, 'Bonita', 'Juarez'),
       (5, 'Marc', 'Spector'),
       (5, 'John', 'Walker'),
       (5, 'Jim', 'Hammond'),
       (5, 'Miguel', 'Santos'),
       (5, 'Julia', 'Carpenter'),
       (5, 'Christopher', 'Powell')
